### ISSUE TITLE
not getting portrait mode if we select full screen from vimeo player

### ISSUE THREAD

**Issue by im-akshay-arora** [studio-b-co-kr/remedi_flutter_plugins#2]
I added remedi_vimeo_player its working fine in android but when I test it on iPhone 12. app stuck on landscape mode it's not getting portrait mode after clicking on the full-screen mode of Vimeo player

**Comment by woogis-code** [comment]
Thanks for your feedback.
Could you describe with images?

If you describe more detail, we can fix faster.

Thanks.

**Comment by woogis-code** [comment]
It's device setting problem.
please set your android or ios env.
