### ISSUE TITLE
토스페이먼츠 질문 드립니다.

### ISSUE THREAD

**Issue by AppLutter** [studio-b-co-kr/remedi_flutter_plugins#4]
웹뷰 내에 x버튼은 없앨 수 없을까요? 또는 x버튼에 대하여 callBack을 받을 수 있을까요?
title과 같은 줄에 있는 x버튼 말고 그 하단에 있는 왼쪽 x 입니다

**Comment by woogis-code** [comment]
답변이 늦어저 죄송합니다.
웹뷰는 토스에서 뿌려주는 것이어서 플로그인 레벨에서는 불가능할 것 같습니다.
